import React, { useMemo, useState } from 'react';
import { motion } from 'motion/react';
import { useApp } from '../context/AppContext';
import { Opportunity, OpportunityCategory, OpportunityType } from '../types';
import { Users, Plus, Send, BriefcaseBusiness, ClipboardCheck, Search, Trash2, Eye, GraduationCap, TrendingUp, MessageSquare, Sparkles, ArrowRightLeft } from 'lucide-react';

export const OrganizationView: React.FC = () => {
  const { registeredUsers, selectedCollege, applications, opportunities, publishCampusOpportunity, removeCampusOpportunity, sendCampusMessage, updateApplicationReviewStatus } = useApp();
  const [search, setSearch] = useState('');
  const [showPublisher, setShowPublisher] = useState(false);
  const [showMessage, setShowMessage] = useState(false);
  const [selectedStudentId, setSelectedStudentId] = useState<string|undefined>();
  const [msgTitle, setMsgTitle] = useState('Campus Update');
  const [msgBody, setMsgBody] = useState('');
  const [form, setForm] = useState({ title:'', type:'Internship' as OpportunityType, category:'Internships' as OpportunityCategory, domain:'Technology', deadline:'2026-10-15', benefit:'Certificate + Mentorship', description:'', skills:'React, JavaScript', mode:'Hybrid' as Opportunity['mode'] });

  const students = useMemo(() => registeredUsers.filter(u => (u.accountType || 'student') === 'student' && (u.collegeCode || u.profile?.collegeCode) === selectedCollege.code).filter(u => `${u.name} ${u.studentId||''} ${u.profile?.degree||''} ${u.profile?.year||''}`.toLowerCase().includes(search.toLowerCase())), [registeredUsers, selectedCollege.code, search]);
  const campusOpps = opportunities.filter(o => o.collegeCode === selectedCollege.code);
  const campusApps = applications.filter(a => a.collegeCode === selectedCollege.code);

  const publish = (e:React.FormEvent) => {
    e.preventDefault();
    const skills=form.skills.split(',').map(s=>s.trim()).filter(Boolean);
    const now=new Date(); const dl=new Date(form.deadline); const days=Math.max(0, Math.ceil((dl.getTime()-now.getTime())/86400000));
    publishCampusOpportunity({
      id:'campus_'+Date.now(), title:form.title, organization:selectedCollege.name, logo:selectedCollege.logoText, type:form.type, category:form.category,
      collegeCode:selectedCollege.code, collegeName:selectedCollege.name, domain:form.domain, location:selectedCollege.city, mode:form.mode, deadline:form.deadline, daysLeft:days,
      duration:'Flexible', stipendOrPrize:form.benefit, applicantsCount:0, interestedCount:0, appliedCount:0, difficulty:'Intermediate', eligibility:'Students of '+selectedCollege.shortName,
      registrationStatus:'Open', requiredSkills:skills, description:form.description || 'Official campus opportunity published by the organization.', matchScore:88, eligibilityScore:96, readinessScore:78, careerImpact:90, priority:'High',
      whyMatch:['Published by your college','Aligned with your student profile'], missingSkills:[], recommendedActions:['Review requirements','Apply before deadline'], status:'Interested'
    });
    setShowPublisher(false); setForm({...form,title:'',description:''});
  };

  return <div className="space-y-6 pb-20">
    <section className="relative overflow-hidden rounded-[30px] bg-[#111018] text-white p-6 sm:p-8 border border-violet-400/20 shadow-xl">
      <div className="absolute -right-24 -top-24 w-72 h-72 rounded-full bg-violet-500/20 blur-3xl"/><div className="absolute left-1/3 -bottom-28 w-72 h-72 rounded-full bg-emerald-500/15 blur-3xl"/>
      <div className="relative z-10 flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div><div className="text-[10px] uppercase tracking-[.22em] font-black text-violet-300">Organization Command Center</div><h1 className="mt-2 text-3xl font-black font-['Outfit',sans-serif]">{selectedCollege.shortName} Opportunity Operations</h1><p className="mt-2 text-sm text-slate-300 max-w-2xl">Track student journeys, publish campus opportunities, review applicants, and send targeted updates from one live workspace.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setShowPublisher(true)} className="px-4 py-3 rounded-xl bg-violet-400 text-slate-950 text-xs font-black flex items-center gap-2"><Plus className="w-4 h-4"/>Add Opportunity</button><button onClick={()=>setShowMessage(true)} className="px-4 py-3 rounded-xl bg-emerald-400 text-slate-950 text-xs font-black flex items-center gap-2"><Send className="w-4 h-4"/>Send Message</button></div></div>
    </section>

    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
      {[['Students',students.length,Users],['Campus Opportunities',campusOpps.length,BriefcaseBusiness],['Applications',campusApps.length,ClipboardCheck],['Avg. Profile Progress',students.length?Math.round(students.reduce((a,u)=>a+Math.min(100,(u.profile.skills.length*8)+(u.profile.projects.length*12)+(u.profile.certifications.length*6)),0)/students.length):0,TrendingUp]].map(([label,val,Icon]:any)=><motion.div whileHover={{y:-3}} key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><Icon className="w-5 h-5 text-violet-700"/><div className="mt-3 text-2xl font-black text-slate-950">{val}{label==='Avg. Profile Progress'?'%':''}</div><div className="text-xs font-bold text-slate-500">{label}</div></motion.div>)}
    </div>

    <section className="rounded-[26px] border border-slate-200 bg-white overflow-hidden shadow-sm">
      <div className="p-5 border-b border-slate-100 flex flex-col sm:flex-row gap-3 sm:items-center justify-between"><div><h2 className="font-black text-slate-950 text-lg">Student Directory & Progress</h2><p className="text-xs text-slate-500">Roll number, class, skills and opportunity journey.</p></div><div className="relative"><Search className="w-4 h-4 absolute left-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student, roll, class..." className="pl-9 pr-3 py-2.5 rounded-xl border border-slate-200 text-xs w-full sm:w-64 outline-none focus:border-violet-400"/></div></div>
      <div className="divide-y divide-slate-100">{students.length===0?<div className="p-8 text-center text-sm text-slate-500">No registered students found for this college yet.</div>:students.map(u=>{const appCount=campusApps.filter(a=>a.studentUserId===u.id).length; const progress=Math.min(100,(u.profile.skills.length*8)+(u.profile.projects.length*12)+(u.profile.certifications.length*6)); return <div key={u.id} className="p-4 sm:p-5 grid lg:grid-cols-[1.4fr_.8fr_.8fr_.7fr_auto] gap-4 items-center hover:bg-violet-50/35 transition-colors"><div className="flex items-center gap-3"><img src={u.profile.avatar} className="w-10 h-10 rounded-xl border border-slate-200"/><div><div className="text-sm font-black text-slate-900">{u.name}</div><div className="text-[11px] text-slate-500 font-mono">{u.studentId || u.profile.studentId}</div></div></div><div><div className="text-[10px] uppercase text-slate-400 font-bold">Class</div><div className="text-xs font-bold">{u.profile.year}</div><div className="text-[10px] text-slate-500">{u.profile.degree}</div></div><div><div className="text-[10px] uppercase text-slate-400 font-bold">Skills</div><div className="text-xs font-bold">{u.profile.skills.slice(0,3).map(s=>s.name).join(', ') || 'Profile pending'}</div></div><div><div className="flex justify-between text-[10px] font-bold"><span>Progress</span><span>{progress}%</span></div><div className="mt-1 h-2 bg-slate-100 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-violet-500 to-emerald-500" style={{width:`${progress}%`}}/></div><div className="mt-1 text-[10px] text-slate-500">{appCount} applications</div></div><button onClick={()=>{setSelectedStudentId(u.id);setMsgTitle(`Message for ${u.name}`);setShowMessage(true)}} className="px-3 py-2 rounded-xl border border-slate-200 text-xs font-black flex items-center gap-1.5 hover:bg-slate-950 hover:text-white"><MessageSquare className="w-3.5 h-3.5"/>Message</button></div>})}</div>
    </section>

    <section className="grid xl:grid-cols-2 gap-5">
      <div className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black text-lg">Published Opportunities</h2><Sparkles className="w-5 h-5 text-emerald-600"/></div><div className="mt-4 space-y-3">{campusOpps.length===0?<p className="text-xs text-slate-500">Publish an internship, hackathon, workshop or event to make it appear on student dashboards.</p>:campusOpps.slice(0,8).map(o=><div key={o.id} className="rounded-2xl bg-slate-50 border border-slate-100 p-3 flex items-center justify-between gap-3"><div><div className="text-xs font-black">{o.title}</div><div className="text-[10px] text-slate-500">{o.type} · {o.deadline} · {o.appliedCount} applied</div></div><button onClick={()=>removeCampusOpportunity(o.id)} className="p-2 rounded-lg text-rose-600 hover:bg-rose-50"><Trash2 className="w-4 h-4"/></button></div>)}</div></div>
      <div className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black text-lg">Latest Applications</h2><ClipboardCheck className="w-5 h-5 text-violet-700"/></div><div className="mt-4 space-y-3">{campusApps.length===0?<p className="text-xs text-slate-500">Student applications will appear here automatically.</p>:campusApps.slice(0,8).map(a=><div key={a.id} className="rounded-2xl bg-slate-50 border border-slate-100 p-3"><div className="flex justify-between gap-3"><div><div className="text-xs font-black">{a.studentName} · {a.studentRoll}</div><div className="text-[10px] text-slate-500">{a.opportunityTitle} · {a.participationType}{a.teamName?` · ${a.teamName}`:''}</div></div><select value={a.status} onChange={e=>updateApplicationReviewStatus(a.id,e.target.value as any)} className="text-[10px] font-bold border border-slate-200 rounded-lg bg-white px-2"><option>Applied</option><option>Under Review</option><option>Shortlisted</option><option>Selected</option><option>Rejected</option></select></div>{a.teamMembers?.length?<div className="mt-2 text-[10px] text-slate-500">Team: {a.teamMembers.join(', ')}</div>:null}</div>)}</div></div>
    </section>

    {showPublisher&&<div className="fixed inset-0 z-[90] bg-slate-950/65 backdrop-blur-sm flex items-center justify-center p-4"><form onSubmit={publish} className="w-full max-w-2xl rounded-[28px] bg-white p-6 shadow-2xl max-h-[90vh] overflow-y-auto"><h3 className="text-xl font-black">Publish Campus Opportunity</h3><p className="text-xs text-slate-500 mt-1">This will be available in the student opportunity feed for {selectedCollege.shortName}.</p><div className="mt-5 grid sm:grid-cols-2 gap-3"><input required placeholder="Opportunity title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="sm:col-span-2 field"/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as any})} className="field"><option>Internship</option><option>Hackathon</option><option>Workshop</option><option>Event</option><option>Competition</option><option>Placement</option></select><select value={form.category} onChange={e=>setForm({...form,category:e.target.value as any})} className="field"><option>Internships</option><option>College Hackathons</option><option>Workshops</option><option>Technical Events</option><option>Competitions</option><option>Placement Opportunities</option></select><input placeholder="Domain" value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})} className="field"/><input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})} className="field"/><input placeholder="Prize / stipend / benefit" value={form.benefit} onChange={e=>setForm({...form,benefit:e.target.value})} className="field"/><input placeholder="Skills, comma separated" value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})} className="field"/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="field sm:col-span-2 min-h-24"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowPublisher(false)} className="px-4 py-2.5 rounded-xl border text-xs font-black">Cancel</button><button className="px-4 py-2.5 rounded-xl bg-violet-700 text-white text-xs font-black">Publish Now</button></div></form></div>}

    {showMessage&&<div className="fixed inset-0 z-[90] bg-slate-950/65 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-[28px] bg-white p-6 shadow-2xl"><h3 className="text-xl font-black">Send Campus Message</h3><input value={msgTitle} onChange={e=>setMsgTitle(e.target.value)} className="field mt-5" placeholder="Title"/><textarea value={msgBody} onChange={e=>setMsgBody(e.target.value)} className="field mt-3 min-h-28" placeholder="Write notification/message..."/><div className="mt-5 flex justify-end gap-2"><button onClick={()=>{setShowMessage(false);setSelectedStudentId(undefined)}} className="px-4 py-2.5 rounded-xl border text-xs font-black">Cancel</button><button onClick={()=>{if(msgBody.trim()){sendCampusMessage(msgTitle,msgBody,selectedStudentId);setMsgBody('');setShowMessage(false);setSelectedStudentId(undefined)}}} className="px-4 py-2.5 rounded-xl bg-emerald-600 text-white text-xs font-black">Send Message</button></div></div></div>}
  </div>;
};
